In [297]:
import os
cwd = r"C:\Users\RahulG\Downloads\Optimization"
os.chdir(cwd)
import pandas as pd, numpy as np,time

In [2]:
from scipy.optimize import minimize
import numpy as np
import pandas as pd

data={"time_studied" : [12, 10, 4, 7, 6, 11, 6,5],\
"hours_slept" : [8, 7, 1, 3, 8, 6, 5,5],\
"TARGET" : [10, 9, 2, 5, 7, 8, 8.5, 6],\
"TARGET1" : [6, 8.5, 8, 7, 5, 2, 9, 10]}


df_temp=pd.DataFrame(data)

# X = np.array([time_studied, hours_slept]).T
# y = np.array([grade]).T 
X=df_temp[["time_studied","hours_slept"]]
y=df_temp["TARGET"]
y1=df_temp["TARGET1"]

In [3]:
from sklearn.ensemble import RandomForestRegressor

In [4]:
model =RandomForestRegressor()
model.fit(X,y)

RandomForestRegressor()

In [5]:
model1 =RandomForestRegressor()
model1.fit(X,y1)

RandomForestRegressor()

In [6]:
model.predict(X)

array([9.23 , 8.81 , 3.535, 5.545, 7.605, 8.285, 7.69 , 6.495])

In [7]:
model1.predict(X)

array([5.23 , 6.74 , 8.16 , 7.53 , 5.885, 3.985, 8.545, 9.355])

In [8]:
#Define Constrains here

bnds = [(5,12), (6,8)]


In [10]:
df_temp.columns

Index(['time_studied', 'hours_slept', 'TARGET', 'TARGET1'], dtype='object')

[7.625, 5.375]

In [16]:
#starting point

x0 = (df_temp[["time_studied",'hours_slept']].mean()).to_list()
x0

[7.625, 5.375]

In [19]:
#Objective func
#-ve sign to maximize

def temp_funct(x):
    NUM=model.predict(np.array([x]))
    DEN=model1.predict(np.array([x]))
    
    return -(NUM/DEN)

In [104]:
method_list=['Nelder-Mead',\
'Powell',\
'CG',\
'BFGS',\
# 'Newton-CG',\
'L-BFGS-B',\
'TNC',\
'COBYLA',\
'SLSQP',\
'trust-constr']#,\
# 'dogleg',\
# 'trust-ncg',\
# 'trust-exact']#,\
# # 'trust-krylov']

In [105]:
meth

'trust-exact'

In [106]:
for meth in method_list:
    result=minimize(temp_funct, x0, method=meth,bounds=bnds,options={'disp': False})
    print(meth)
    print(result.x)
    print(result.fun)
    print("\n")

c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method Nelder-Mead cannot handle constraints nor bounds.
  RuntimeWarning)


Nelder-Mead
[8.00625 5.64375]
-1.113555713271824




c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method Powell cannot handle constraints nor bounds.
  RuntimeWarning)


Powell
[19.54135773  6.71648593]
-1.9408033826638476


CG
[7.625 5.375]
[-0.87995269]


BFGS
[7.625 5.375]
[-0.87995269]


L-BFGS-B
[7.625 6.   ]
[-1.07197764]


TNC

c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method CG cannot handle constraints nor bounds.
  RuntimeWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)



[7.625 6.   ]
[-1.07197764]


COBYLA
[8.79618239 6.55719931]
-1.243795620437956


SLSQP
[7.625 6.   ]
-1.0719776380153738


trust-constr
[7.50080386 6.00141574]
[-1.11311239]




c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:528: RuntimeWarning: Method COBYLA cannot handle bounds.
  RuntimeWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)


In [109]:
result=minimize(temp_funct, x0, method='trust-constr',bounds=bnds,options={'disp': True})

`gtol` termination condition is satisfied.
Number of iterations: 12, function evaluations: 9, CG iterations: 3, optimality: 7.52e-09, constraint violation: 0.00e+00, execution time: 0.11 s.


c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)


In [110]:
#show the result
result.x

array([7.50080386, 6.00141574])

In [111]:
result.fun

array([-1.11311239])

In [112]:
result.message

'`gtol` termination condition is satisfied.'

### Black box optimizer

In [171]:
from yabox import DE

In [174]:
de=DE(temp_funct,bnds,maxiters=1000)

In [175]:
de.solve(show_progress=True)

(array([[11.1706256,  6.8662498]]), array([-2.16957606]))

### result cross checking

In [139]:
bnds

[(5, 12), (6, 8)]

In [147]:
sample_point_feature1=0.25
sample_point_feature2=0.25

In [140]:
Feature1=np.arange(bnds[0][0],bnds[0][1],sample_point_feature1)

In [148]:
Feature2=np.arange(bnds[1][0],bnds[1][1],sample_point_feature2)

In [149]:
Feature1

array([ 5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,
        7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,
        9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 ,
       11.75])

In [150]:
Feature2

array([6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75])

In [151]:
len(Feature1),len(Feature2),len(Feature1)*len(Feature2)

(28, 8, 224)

In [152]:
temp_list=[]

In [153]:
for i in Feature1:
    for j in Feature2:
        temp_list.append([i,j])

In [154]:
temp_list

[[5.0, 6.0],
 [5.0, 6.25],
 [5.0, 6.5],
 [5.0, 6.75],
 [5.0, 7.0],
 [5.0, 7.25],
 [5.0, 7.5],
 [5.0, 7.75],
 [5.25, 6.0],
 [5.25, 6.25],
 [5.25, 6.5],
 [5.25, 6.75],
 [5.25, 7.0],
 [5.25, 7.25],
 [5.25, 7.5],
 [5.25, 7.75],
 [5.5, 6.0],
 [5.5, 6.25],
 [5.5, 6.5],
 [5.5, 6.75],
 [5.5, 7.0],
 [5.5, 7.25],
 [5.5, 7.5],
 [5.5, 7.75],
 [5.75, 6.0],
 [5.75, 6.25],
 [5.75, 6.5],
 [5.75, 6.75],
 [5.75, 7.0],
 [5.75, 7.25],
 [5.75, 7.5],
 [5.75, 7.75],
 [6.0, 6.0],
 [6.0, 6.25],
 [6.0, 6.5],
 [6.0, 6.75],
 [6.0, 7.0],
 [6.0, 7.25],
 [6.0, 7.5],
 [6.0, 7.75],
 [6.25, 6.0],
 [6.25, 6.25],
 [6.25, 6.5],
 [6.25, 6.75],
 [6.25, 7.0],
 [6.25, 7.25],
 [6.25, 7.5],
 [6.25, 7.75],
 [6.5, 6.0],
 [6.5, 6.25],
 [6.5, 6.5],
 [6.5, 6.75],
 [6.5, 7.0],
 [6.5, 7.25],
 [6.5, 7.5],
 [6.5, 7.75],
 [6.75, 6.0],
 [6.75, 6.25],
 [6.75, 6.5],
 [6.75, 6.75],
 [6.75, 7.0],
 [6.75, 7.25],
 [6.75, 7.5],
 [6.75, 7.75],
 [7.0, 6.0],
 [7.0, 6.25],
 [7.0, 6.5],
 [7.0, 6.75],
 [7.0, 7.0],
 [7.0, 7.25],
 [7.0, 7.5],
 [7.0, 7.7

In [155]:
len(temp_list)

224

In [156]:
df_test=pd.DataFrame(data=temp_list,columns=["Feature1","Feature2"])

In [157]:
df_test.head()

Feature1  Feature2
0       5.0      6.00
1       5.0      6.25
2       5.0      6.50
3       5.0      6.75
4       5.0      7.00

In [158]:
df_test.values

array([[ 5.  ,  6.  ],
       [ 5.  ,  6.25],
       [ 5.  ,  6.5 ],
       [ 5.  ,  6.75],
       [ 5.  ,  7.  ],
       [ 5.  ,  7.25],
       [ 5.  ,  7.5 ],
       [ 5.  ,  7.75],
       [ 5.25,  6.  ],
       [ 5.25,  6.25],
       [ 5.25,  6.5 ],
       [ 5.25,  6.75],
       [ 5.25,  7.  ],
       [ 5.25,  7.25],
       [ 5.25,  7.5 ],
       [ 5.25,  7.75],
       [ 5.5 ,  6.  ],
       [ 5.5 ,  6.25],
       [ 5.5 ,  6.5 ],
       [ 5.5 ,  6.75],
       [ 5.5 ,  7.  ],
       [ 5.5 ,  7.25],
       [ 5.5 ,  7.5 ],
       [ 5.5 ,  7.75],
       [ 5.75,  6.  ],
       [ 5.75,  6.25],
       [ 5.75,  6.5 ],
       [ 5.75,  6.75],
       [ 5.75,  7.  ],
       [ 5.75,  7.25],
       [ 5.75,  7.5 ],
       [ 5.75,  7.75],
       [ 6.  ,  6.  ],
       [ 6.  ,  6.25],
       [ 6.  ,  6.5 ],
       [ 6.  ,  6.75],
       [ 6.  ,  7.  ],
       [ 6.  ,  7.25],
       [ 6.  ,  7.5 ],
       [ 6.  ,  7.75],
       [ 6.25,  6.  ],
       [ 6.25,  6.25],
       [ 6.25,  6.5 ],
       [ 6.

In [159]:
df_test=df_test.assign(Ratio=model.predict(np.array(df_test[["Feature1","Feature2"]]))/model1.predict(np.array(df_test[["Feature1","Feature2"]])))

In [160]:
df_test.sort_values("Ratio",ascending=False).head()

Feature1  Feature2     Ratio
203     11.25      6.75  2.169576
204     11.25      7.00  2.169576
211     11.50      6.75  2.169576
212     11.50      7.00  2.169576
202     11.25      6.50  2.143949

In [167]:
result.x[0]

7.500803858726402

In [170]:
df_test[(df_test["Feature1"]>result.x[0]-sample_point_feature1) & \
        (df_test["Feature1"]<result.x[0]+sample_point_feature1) & \
        (df_test["Feature2"]>result.x[1]-sample_point_feature2) & \
        (df_test["Feature2"]<result.x[1]+sample_point_feature2)
       ].sort_values("Ratio",ascending=False)

Feature1  Feature2     Ratio
89      7.75      6.25  1.113112
81      7.50      6.25  1.108321
88      7.75      6.00  1.071978
80      7.50      6.00  1.067502

In [169]:
result.x,result.fun

(array([7.50080386, 6.00141574]), array([-1.11311239]))

# HYDROCRACKER OPTIMIZATION

In [188]:
#********************************PKL FILES*************************************
mdl_StageI_LN = pd.read_pickle("./StageI_LN.pkl")
mdl_StageI_HN = pd.read_pickle("./StageI_HN.pkl")
mdl_StageI_KERO = pd.read_pickle("./StageI_KERO.pkl")
mdl_StageI_DIESEL = pd.read_pickle("./StageI_DIESEL.pkl")
mdl_StageII_LN = pd.read_pickle("./StageII_LN.pkl")
mdl_StageII_HN = pd.read_pickle("./StageII_HN.pkl")
mdl_StageII_KERO = pd.read_pickle("./StageII_KERO.pkl")
mdl_StageII_DIESEL = pd.read_pickle("./StageII_DIESEL.pkl")


In [189]:
DIESELI = pd.read_excel("./Stage-I_Order.xlsx",sheet_name = "DIESEL")
DIESELI_FEATURES=DIESELI["SI_DIESEL"].to_list()

DIESELII = pd.read_excel("./Stage-II_Order.xlsx",sheet_name = "DIESEL")
DIESELII_FEATURES=DIESELII["SII_DIESEL"].to_list()

In [190]:
LNI = pd.read_excel("./Stage-I_Order.xlsx",sheet_name = "LN")
LNI_FEATURES=LNI["SI_LN"].to_list()

In [225]:
len(DIESELI_FEATURES)

35

In [226]:
# DIESELI_FEATURES constrains
df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="DIESELI").set_index("DIESELI").to_dict()
DIESELI_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in DIESELI_FEATURES]

In [227]:
DIESELI_CONSTRAINTS,len(DIESELI_CONSTRAINTS)

([(4.630089639504766, 6.214104143349605),
  (45.20059502227286, 59.95955023603791),
  (0.0008906249800929802, 0.07999999821186066),
  (0.0, 0.112874997477047),
  (3.081562449783087, 3.589999914169312),
  (934.0, 940.4000244140625),
  (268.2899902343751, 291.4299896240234),
  (334.160009765625, 353.2600097656249),
  (359.5, 375.8500106811522),
  (3.140000104904175, 3.779999971389771),
  (408.3, 1107.6),
  (0.2901484294561669, 1.129999982208014),
  (0.05999999865889553, 0.1000000014901161),
  (2253.875, 2681.575),
  (0.2101484310231171, 0.3005000103265046),
  (61.00000000000009, 104.000537109375),
  (298.170423884969, 383.9116592266704),
  (2.419806635057847, 4.970239427057197),
  (8.933823297732516, 12.29716086853779),
  (5.566371265513738, 13.6828152166717),
  (5.432969040268341, 11.56198206082573),
  (5.231197756116598, 7.648287564487043),
  (348.6406429481298, 355.4215352508965),
  (370.8172109959908, 380.9191503034329),
  (371.9049938220198, 385.1036043718777),
  (378.4089686642804,

In [229]:
DIESELII_FEATURES,len(DIESELII_FEATURES)

(['SII_E-1048_RECY_GAS_FEED',
  'SII_OIL_FEED_TO_E-1048/49',
  'SII_Gravity',
  'SII_Distillate_BP_(30%)_(D-86)',
  'SII_Distillate_BP_(50%)_(D-86)',
  'SII_Distillate_BP_(70%)_(D-86)',
  'SII_Distillate_BP_(80%)_(D-86)',
  'SII_Distillate_BP_(90%)_(D-86)',
  'SII_Distillate_BP_(95%)_(D-86)',
  'SII_Distillate_BP_(FBP)_(D-86)',
  'SII_Sulfur',
  'SII_Nitrogen',
  'SII_C-1002_QNCH_GAS_BEDS_I',
  'SII_C-1002_QNCH_GAS_BEDS_II',
  'SII_C1002_FEED_FROM_F1002',
  'SII_Bed_1_Inlet',
  'SII_Bed_2_Inlet',
  'SII_Bed_3_Inlet',
  'SII_Bed_1_Outlet',
  'SII_Bed_2_Outlet',
  'SII_Bed_3_Outlet',
  'SII_E-1051_MP_STM_TO_HDR',
  'SII_E-1051_T/S_OUTLET'],
 23)

In [230]:
# DIESELII_FEATURES constrains
df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="DIESELII").set_index("DIESELII").to_dict()
DIESELII_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in DIESELII_FEATURES]

In [231]:
DIESELII_CONSTRAINTS,len(DIESELII_CONSTRAINTS)

([(31.99584367230782, 41.29916463656569),
  (190.14709248435, 253.2622410085752),
  (847.5, 856.5),
  (402.7000122070312, 427.9399932861328),
  (429.2999877929688, 454.2500122070311),
  (459.6000061035156, 484.05),
  (479.5, 503.3799896240234),
  (508.8999938964844, 533.2300109863281),
  (531.5899780273438, 554.2300109863281),
  (576.4799987792969, 597.1400024414063),
  (4.0, 11.24999980926512),
  (0.2000000029802322, 2.5),
  (1116.413475779643, 3061.767139306549),
  (1298.428124605859, 2568.854099575245),
  (359.497887874547, 367.8582995198164),
  (359.276249278821, 367.653274267207),
  (363.3537611383899, 373.6731086000511),
  (367.1716599524207, 377.8416189732227),
  (367.5991924527128, 376.5170002928178),
  (370.1900241071291, 382.3690604446756),
  (374.4848818715437, 387.6802708878436),
  (4.089685744735435, 8.972605709449882),
  (240.9754662966794, 255.9096844988991)],
 23)

In [232]:
LNI_FEATURES,len(LNI_FEATURES)

(['SI_MKUP_H2_FROM_K0002/3/4/5',
  'SI_RECYCLE_GAS_TO_F-1001',
  'SI_H2',
  'SI_CH4',
  'SI_C2H6',
  'SI_C3H8',
  'SI_NC4',
  'SI_NC5',
  'SI_C6+',
  'SI_Avg_MW',
  'SI_Gravity',
  'SI_Distillate_BP_(5%)',
  'SI_Sulfur',
  'SI_Nitrogen',
  'SI_Vanadium_(V)',
  'SI_Nickel_(Ni)',
  'SI_PCI',
  'SI_CCR',
  'SI_Asphaltenes',
  'SI_G-1001/02_TO_F-1001',
  'SI_C-1001_QNCH_GAS_BED2',
  'SI_C-1001_QNCH_GAS_BED3',
  'SI_C-1001_QNCH_GAS_BED4',
  'SI_C-1001_QNCH_GAS_BED5',
  'SI_C-1001_QNCH_GAS_BED6',
  'SI_Bed_1_Inlet',
  'SI_Bed_2_Inlet',
  'SI_Bed_3_Inlet',
  'SI_Bed_4_Inlet',
  'SI_Bed_5_Inlet',
  'SI_Bed_6_Inlet',
  'SI_Bed_1_Outlet',
  'SI_Bed_2_Outlet',
  'SI_Bed_3_Outlet',
  'SI_Bed_4_Outlet',
  'SI_Bed_5_Outlet',
  'SI_Bed_6_Outlet',
  'SI_E-1044_T/S_OUTLET'],
 38)

In [209]:
# LNI_FEATURES constrains
df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="LNI").set_index("LNI").to_dict()
LNI_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in LNI_FEATURES]

In [233]:
LNI_CONSTRAINTS,len(LNI_CONSTRAINTS)

([(4.630089639504766, 6.214104143349605),
  (45.20059502227286, 59.95955023603791),
  (95.70999908447266, 96.71199913024903),
  (1.159999966621399, 1.649999976158142),
  (0.3600000143051147, 0.5399995064734184),
  (0.449999988079071, 0.6299999952316284),
  (0.1899999976158142, 0.2899999916553497),
  (0.0008906249800929802, 0.07999999821186066),
  (0.09000000357627869, 0.2000000029802322),
  (3.081562449783087, 3.589999914169312),
  (934.0, 940.4000244140625),
  (334.160009765625, 353.2600097656249),
  (3.140000104904175, 3.779999971389771),
  (408.3, 1107.6),
  (0.2901484294561669, 1.129999982208014),
  (0.05999999865889553, 0.1000000014901161),
  (2253.875, 2681.575),
  (0.2101484310231171, 0.3005000103265046),
  (61.00000000000009, 104.000537109375),
  (298.170423884969, 383.9116592266704),
  (2.419806635057847, 4.970239427057197),
  (8.933823297732516, 12.29716086853779),
  (5.566371265513738, 13.6828152166717),
  (5.432969040268341, 11.56198206082573),
  (5.231197756116598, 7.64828

In [257]:
# LNII_FEATURES constrains

LNII = pd.read_excel("./Stage-II_Order.xlsx",sheet_name = "LN")
LNII_FEATURES=LNII["SII_LN"].to_list()

df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="LNII").set_index("LNII").to_dict()
LNII_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in LNII_FEATURES]

In [283]:
len(LNII_FEATURES)==len(LNII_CONSTRAINTS)

True

In [262]:
# HNI 

HNI = pd.read_excel("./Stage-I_Order.xlsx",sheet_name = "HN")
HNI_FEATURES=HNI["SI_HN"].to_list()

df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="HNI").set_index("HNI").to_dict()
HNI_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in HNI_FEATURES]

In [284]:
len(HNI_FEATURES)==len(HNI_CONSTRAINTS)

True

In [285]:
# HNII

HNII = pd.read_excel("./Stage-II_Order.xlsx",sheet_name = "HN")
HNII_FEATURES=HNII["SII_HN"].to_list()

df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="HNII").set_index("HNII").to_dict()
HNII_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in HNII_FEATURES]

In [286]:
len(HNII_FEATURES)==len(HNII_CONSTRAINTS)

True

In [273]:
# KEROI 

KEROI = pd.read_excel("./Stage-I_Order.xlsx",sheet_name = "KERO")
KEROI_FEATURES=KEROI["SI_KERO"].to_list()

df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="KEROI").set_index("KEROI").to_dict()
KEROI_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in KEROI_FEATURES]

In [287]:
len(KEROI_FEATURES)==len(KEROI_CONSTRAINTS)

True

In [275]:
# KEROII

KEROII = pd.read_excel("./Stage-II_Order.xlsx",sheet_name = "KERO")
KEROII_FEATURES=KEROII["SII_KERO"].to_list()

df_ucl_lcl_d1=pd.read_excel(r"C:\Users\RahulG\Downloads\LL_UL.xlsx",sheet_name="KEROII").set_index("KEROII").to_dict()
KEROII_CONSTRAINTS=[(df_ucl_lcl_d1["LL"][x],df_ucl_lcl_d1["UL"][x]) for x in KEROII_FEATURES]

In [288]:
len(KEROII_FEATURES)==len(KEROII_CONSTRAINTS)

True

In [289]:
ALL_CONSTRAINTS=DIESELI_CONSTRAINTS+DIESELII_CONSTRAINTS+LNI_CONSTRAINTS+LNII_CONSTRAINTS+HNI_CONSTRAINTS+HNII_CONSTRAINTS\
+KEROI_CONSTRAINTS+KEROII_CONSTRAINTS

In [290]:
len(ALL_CONSTRAINTS),len(DIESELI_CONSTRAINTS),len(DIESELII_CONSTRAINTS),len(LNI_CONSTRAINTS),len(LNII_CONSTRAINTS),len(HNI_CONSTRAINTS),len(HNII_CONSTRAINTS),len(KEROI_CONSTRAINTS),len(KEROII_CONSTRAINTS)

(234, 35, 23, 38, 23, 36, 21, 35, 23)

In [291]:
# This should be True
print("This Should be true")
len(ALL_CONSTRAINTS)==len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)+len(KEROI_CONSTRAINTS)+len(KEROII_CONSTRAINTS)

This Should be true


True

In [238]:
# temp_x_dieselI=ALL_CONSTRAINTS[:len(DIESELI_CONSTRAINTS)]
# temp_x_dieselII=ALL_CONSTRAINTS[len(DIESELI_CONSTRAINTS):len(DIESELII_CONSTRAINTS)+1]
# temp_x_LNI=ALL_CONSTRAINTS[len(DIESELII_CONSTRAINTS):]
    

In [239]:
# len(temp_x_dieselI)

35

In [292]:
#Define Objective Problem

def obj_func(x):
    """
    Defining optimization objective function using predictive model here
    
    obj = cp.Maximize(((mdl_StageI_DIESEL.predict(DIESELI)[0])+(mdl_StageII_DIESEL.predict(DIESELII)[0]))/\
    ((mdl_StageI_DIESEL.predict(DIESELI)[0])+(mdl_StageII_DIESEL.predict(DIESELII)[0])+(mdl_StageI_LN.predict(LNI)[0])\
    +(mdl_StageII_LN.predict(LNII)[0])+\
    (mdl_StageI_HN.predict(HNI)[0])+\
    (mdl_StageII_HN.predict(HNII)[0])+\
    (mdl_StageI_KERO.predict(KEROI)[0])+\
    (mdl_StageII_KERO.predict(KEROII)[0])))
    # 
    """  
    x_dieselI=x[:len(DIESELI_CONSTRAINTS)]
    x_dieselII=x[len(DIESELI_CONSTRAINTS):len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)]
    x_LNI=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS):len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)]
    x_LNII=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS):\
            len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)]
    x_HNI=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)
            :len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)        
    ]
    x_HNII=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)
            :len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)
    ]
    x_KEROI=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)
              :len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)+len(KEROI_CONSTRAINTS)
              ]
    x_KEROII=x[len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)+len(KEROI_CONSTRAINTS)
              :len(DIESELI_CONSTRAINTS)+len(DIESELII_CONSTRAINTS)+len(LNI_CONSTRAINTS)+len(LNII_CONSTRAINTS)+len(HNI_CONSTRAINTS)+len(HNII_CONSTRAINTS)+len(KEROI_CONSTRAINTS)+len(KEROII_CONSTRAINTS)
              
              ]
    
    
    NUMERATOR=(mdl_StageI_DIESEL.predict([x_dieselI])[0])+(mdl_StageII_DIESEL.predict([x_dieselII])[0])
    
    DENOMINATOR=(NUMERATOR+\
                 (mdl_StageI_LN.predict([x_LNI])[0])+(mdl_StageII_LN.predict([x_LNII])[0])+\
                 (mdl_StageI_HN.predict([x_HNI])[0])+(mdl_StageII_HN.predict([x_HNII])[0])+\
                 (mdl_StageI_KERO.predict([x_KEROI])[0])+(mdl_StageII_KERO.predict([x_KEROII])[0])                 
                )    
    
    return (NUMERATOR/DENOMINATOR)

In [294]:
de_hc=DE(obj_func,ALL_CONSTRAINTS,maxiters=2)

In [295]:
de_hc.solve(show_progress=True)

(array([[5.02172752e+00, 5.39047970e+01, 2.94913384e-02, 7.60929929e-02,
         3.15246153e+00, 9.36791731e+02, 2.81213715e+02, 3.38927523e+02,
         3.62732824e+02, 3.68559206e+00, 9.26885242e+02, 7.39693913e-01,
         6.31921047e-02, 2.62332894e+03, 2.39344179e-01, 6.48824659e+01,
         3.27138386e+02, 3.77172295e+00, 9.05485276e+00, 6.69954801e+00,
         8.66685684e+00, 7.11376585e+00, 3.51166433e+02, 3.71845683e+02,
         3.81137112e+02, 3.91776858e+02, 3.86807791e+02, 3.83241961e+02,
         3.82414365e+02, 3.92011183e+02, 4.09045095e+02, 4.00507259e+02,
         4.08454567e+02, 4.03593604e+02, 2.55367166e+02, 3.99781851e+01,
         2.31401961e+02, 8.56214575e+02, 4.10204984e+02, 4.33198531e+02,
         4.66206082e+02, 4.83940727e+02, 5.12769706e+02, 5.53305101e+02,
         5.90111627e+02, 1.04735928e+01, 3.55298500e-01, 1.83368825e+03,
         1.67532606e+03, 3.60860217e+02, 3.64245602e+02, 3.70829758e+02,
         3.71954573e+02, 3.68535369e+02, 3.74257799

In [316]:
import yabox

In [312]:
start=time.time()

de_hc1=DE(obj_func,ALL_CONSTRAINTS,maxiters=10)

x1,x2=de_hc1.solve(show_progress=True)

end=time.time()

In [303]:
(end-start)/3600

1.0688645298613442

### SCIPY DE

In [305]:
from scipy.optimize import differential_evolution

In [311]:
%%time
result = differential_evolution(obj_func, ALL_CONSTRAINTS,disp=True,maxiter=2)

differential_evolution step 1: f(x)= 0.551284
differential_evolution step 2: f(x)= 0.549005
Wall time: 1h 23min 33s
