In [1]:
import os
cwd = r"C:\Users\RahulG\Downloads\Optimization"
os.chdir(cwd)
import pandas as pd, numpy as np

In [2]:
from scipy.optimize import minimize
import numpy as np
import pandas as pd

data={"time_studied" : [12, 10, 4, 7, 6, 11, 6,5],\
"hours_slept" : [8, 7, 1, 3, 8, 6, 5,5],\
"TARGET" : [10, 9, 2, 5, 7, 8, 8.5, 6],\
"TARGET1" : [6, 8.5, 8, 7, 5, 2, 9, 10]}


df_temp=pd.DataFrame(data)

# X = np.array([time_studied, hours_slept]).T
# y = np.array([grade]).T 
X=df_temp[["time_studied","hours_slept"]]
y=df_temp["TARGET"]
y1=df_temp["TARGET1"]

In [3]:
from sklearn.ensemble import RandomForestRegressor

In [4]:
model =RandomForestRegressor()
model.fit(X,y)

RandomForestRegressor()

In [5]:
model1 =RandomForestRegressor()
model1.fit(X,y1)

RandomForestRegressor()

In [6]:
model.predict(X)

array([9.23 , 8.81 , 3.535, 5.545, 7.605, 8.285, 7.69 , 6.495])

In [7]:
model1.predict(X)

array([5.23 , 6.74 , 8.16 , 7.53 , 5.885, 3.985, 8.545, 9.355])

In [8]:
#Define Constrains here

bnds = [(5,12), (6,8)]


In [10]:
df_temp.columns

Index(['time_studied', 'hours_slept', 'TARGET', 'TARGET1'], dtype='object')

[7.625, 5.375]

In [16]:
#starting point

x0 = (df_temp[["time_studied",'hours_slept']].mean()).to_list()
x0

[7.625, 5.375]

In [19]:
#Objective func
#-ve sign to maximize

def temp_funct(x):
    NUM=model.predict(np.array([x]))
    DEN=model1.predict(np.array([x]))
    
    return -(NUM/DEN)

In [104]:
method_list=['Nelder-Mead',\
'Powell',\
'CG',\
'BFGS',\
# 'Newton-CG',\
'L-BFGS-B',\
'TNC',\
'COBYLA',\
'SLSQP',\
'trust-constr']#,\
# 'dogleg',\
# 'trust-ncg',\
# 'trust-exact']#,\
# # 'trust-krylov']

In [105]:
meth

'trust-exact'

In [106]:
for meth in method_list:
    result=minimize(temp_funct, x0, method=meth,bounds=bnds,options={'disp': False})
    print(meth)
    print(result.x)
    print(result.fun)
    print("\n")

c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method Nelder-Mead cannot handle constraints nor bounds.
  RuntimeWarning)


Nelder-Mead
[8.00625 5.64375]
-1.113555713271824




c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method Powell cannot handle constraints nor bounds.
  RuntimeWarning)


Powell
[19.54135773  6.71648593]
-1.9408033826638476


CG
[7.625 5.375]
[-0.87995269]


BFGS
[7.625 5.375]
[-0.87995269]


L-BFGS-B
[7.625 6.   ]
[-1.07197764]


TNC

c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method CG cannot handle constraints nor bounds.
  RuntimeWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:522: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)



[7.625 6.   ]
[-1.07197764]


COBYLA
[8.79618239 6.55719931]
-1.243795620437956


SLSQP
[7.625 6.   ]
-1.0719776380153738


trust-constr
[7.50080386 6.00141574]
[-1.11311239]




c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py:528: RuntimeWarning: Method COBYLA cannot handle bounds.
  RuntimeWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)


In [109]:
result=minimize(temp_funct, x0, method='trust-constr',bounds=bnds,options={'disp': True})

`gtol` termination condition is satisfied.
Number of iterations: 12, function evaluations: 9, CG iterations: 3, optimality: 7.52e-09, constraint violation: 0.00e+00, execution time: 0.11 s.


c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)
c:\users\rahulg\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)


In [110]:
#show the result
result.x

array([7.50080386, 6.00141574])

In [111]:
result.fun

array([-1.11311239])

In [112]:
result.message

'`gtol` termination condition is satisfied.'

### result cross checking

In [139]:
bnds

[(5, 12), (6, 8)]

In [147]:
sample_point_feature1=0.25
sample_point_feature2=0.25

In [140]:
Feature1=np.arange(bnds[0][0],bnds[0][1],sample_point_feature1)

In [148]:
Feature2=np.arange(bnds[1][0],bnds[1][1],sample_point_feature2)

In [149]:
Feature1

array([ 5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,
        7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,
        9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 ,
       11.75])

In [150]:
Feature2

array([6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75])

In [151]:
len(Feature1),len(Feature2),len(Feature1)*len(Feature2)

(28, 8, 224)

In [152]:
temp_list=[]

In [153]:
for i in Feature1:
    for j in Feature2:
        temp_list.append([i,j])

In [154]:
temp_list

[[5.0, 6.0],
 [5.0, 6.25],
 [5.0, 6.5],
 [5.0, 6.75],
 [5.0, 7.0],
 [5.0, 7.25],
 [5.0, 7.5],
 [5.0, 7.75],
 [5.25, 6.0],
 [5.25, 6.25],
 [5.25, 6.5],
 [5.25, 6.75],
 [5.25, 7.0],
 [5.25, 7.25],
 [5.25, 7.5],
 [5.25, 7.75],
 [5.5, 6.0],
 [5.5, 6.25],
 [5.5, 6.5],
 [5.5, 6.75],
 [5.5, 7.0],
 [5.5, 7.25],
 [5.5, 7.5],
 [5.5, 7.75],
 [5.75, 6.0],
 [5.75, 6.25],
 [5.75, 6.5],
 [5.75, 6.75],
 [5.75, 7.0],
 [5.75, 7.25],
 [5.75, 7.5],
 [5.75, 7.75],
 [6.0, 6.0],
 [6.0, 6.25],
 [6.0, 6.5],
 [6.0, 6.75],
 [6.0, 7.0],
 [6.0, 7.25],
 [6.0, 7.5],
 [6.0, 7.75],
 [6.25, 6.0],
 [6.25, 6.25],
 [6.25, 6.5],
 [6.25, 6.75],
 [6.25, 7.0],
 [6.25, 7.25],
 [6.25, 7.5],
 [6.25, 7.75],
 [6.5, 6.0],
 [6.5, 6.25],
 [6.5, 6.5],
 [6.5, 6.75],
 [6.5, 7.0],
 [6.5, 7.25],
 [6.5, 7.5],
 [6.5, 7.75],
 [6.75, 6.0],
 [6.75, 6.25],
 [6.75, 6.5],
 [6.75, 6.75],
 [6.75, 7.0],
 [6.75, 7.25],
 [6.75, 7.5],
 [6.75, 7.75],
 [7.0, 6.0],
 [7.0, 6.25],
 [7.0, 6.5],
 [7.0, 6.75],
 [7.0, 7.0],
 [7.0, 7.25],
 [7.0, 7.5],
 [7.0, 7.7

In [155]:
len(temp_list)

224

In [156]:
df_test=pd.DataFrame(data=temp_list,columns=["Feature1","Feature2"])

In [157]:
df_test.head()

Feature1  Feature2
0       5.0      6.00
1       5.0      6.25
2       5.0      6.50
3       5.0      6.75
4       5.0      7.00

In [158]:
df_test.values

array([[ 5.  ,  6.  ],
       [ 5.  ,  6.25],
       [ 5.  ,  6.5 ],
       [ 5.  ,  6.75],
       [ 5.  ,  7.  ],
       [ 5.  ,  7.25],
       [ 5.  ,  7.5 ],
       [ 5.  ,  7.75],
       [ 5.25,  6.  ],
       [ 5.25,  6.25],
       [ 5.25,  6.5 ],
       [ 5.25,  6.75],
       [ 5.25,  7.  ],
       [ 5.25,  7.25],
       [ 5.25,  7.5 ],
       [ 5.25,  7.75],
       [ 5.5 ,  6.  ],
       [ 5.5 ,  6.25],
       [ 5.5 ,  6.5 ],
       [ 5.5 ,  6.75],
       [ 5.5 ,  7.  ],
       [ 5.5 ,  7.25],
       [ 5.5 ,  7.5 ],
       [ 5.5 ,  7.75],
       [ 5.75,  6.  ],
       [ 5.75,  6.25],
       [ 5.75,  6.5 ],
       [ 5.75,  6.75],
       [ 5.75,  7.  ],
       [ 5.75,  7.25],
       [ 5.75,  7.5 ],
       [ 5.75,  7.75],
       [ 6.  ,  6.  ],
       [ 6.  ,  6.25],
       [ 6.  ,  6.5 ],
       [ 6.  ,  6.75],
       [ 6.  ,  7.  ],
       [ 6.  ,  7.25],
       [ 6.  ,  7.5 ],
       [ 6.  ,  7.75],
       [ 6.25,  6.  ],
       [ 6.25,  6.25],
       [ 6.25,  6.5 ],
       [ 6.

In [159]:
df_test=df_test.assign(Ratio=model.predict(np.array(df_test[["Feature1","Feature2"]]))/model1.predict(np.array(df_test[["Feature1","Feature2"]])))

In [160]:
df_test.sort_values("Ratio",ascending=False).head()

Feature1  Feature2     Ratio
203     11.25      6.75  2.169576
204     11.25      7.00  2.169576
211     11.50      6.75  2.169576
212     11.50      7.00  2.169576
202     11.25      6.50  2.143949

In [167]:
result.x[0]

7.500803858726402

In [170]:
df_test[(df_test["Feature1"]>result.x[0]-sample_point_feature1) & \
        (df_test["Feature1"]<result.x[0]+sample_point_feature1) & \
        (df_test["Feature2"]>result.x[1]-sample_point_feature2) & \
        (df_test["Feature2"]<result.x[1]+sample_point_feature2)
       ].sort_values("Ratio",ascending=False)

Feature1  Feature2     Ratio
89      7.75      6.25  1.113112
81      7.50      6.25  1.108321
88      7.75      6.00  1.071978
80      7.50      6.00  1.067502

In [169]:
result.x,result.fun

(array([7.50080386, 6.00141574]), array([-1.11311239]))